# Generated by Django 4.2.7 on 2023-12-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="picture",
            field=models.ImageField(upload_to="./static/fleit/images"),
        ),
    ]
