# Generated by Django 4.2.7 on 2023-12-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleit", "0002_alter_destination_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="picture",
            field=models.ImageField(upload_to="./fleit/static/fleit/images"),
        ),
    ]
