# Generated by Django 4.2.7 on 2023-12-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleit", "0003_alter_destination_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="picture",
            field=models.ImageField(upload_to=".media/images"),
        ),
    ]
