# Generated by Django 4.2.7 on 2023-12-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleit", "0005_alter_destination_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="description",
            field=models.CharField(default="Visit today.", max_length=200),
        ),
    ]
