# Generated by Django 4.2.7 on 2023-12-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleit", "0006_destination_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="picture",
            field=models.ImageField(upload_to="destination_images"),
        ),
    ]
